//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public System.DateTime TimeStart { get; set; }
        public System.DateTime TimeEnd { get; set; }
        public string Client { get; set; }
        public string Patient { get; set; }
        public string Description { get; set; }
        public int ProcedureTime { get; set; }
        public int DoctorID { get; set; }
        public string Doctor { get; set; }
        public Nullable<int> ExamRoomNumber { get; set; }
    }
}
