//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ClientId { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public Nullable<int> ZIP { get; set; }
        public string County { get; set; }
        public string Company { get; set; }
        public Nullable<int> FaxNumber { get; set; }
        public Nullable<int> FirstPhoneNumAC { get; set; }
        public Nullable<int> FirstPhoneNum { get; set; }
        public Nullable<int> SecondPhoneNumAC { get; set; }
        public Nullable<int> SecondPhoneNum { get; set; }
        public string FirstPhoneNumType { get; set; }
        public string SecondPhoneNumType { get; set; }
        public Nullable<int> Folder { get; set; }
        public Nullable<int> Co_ { get; set; }
        public string Title { get; set; }
        public string Codes { get; set; }
        public string Class { get; set; }
        public Nullable<double> BalanceDue { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
