//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Position { get; set; }
        public Nullable<int> AccessLevel { get; set; }
        public bool IsDoctor { get; set; }
        public string Username { get; set; }
        public Nullable<bool> IsFullTime { get; set; }
        public bool IsWorking { get; set; }
        public bool IsOnLunchBreak { get; set; }
    }
}
