//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeChanx
    {
        public int Id { get; set; }
        public string ChangeType { get; set; }
        public string Description { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeInitials { get; set; }
    }
}
