//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kennel
    {
        public int Id { get; set; }
        public string KennelID { get; set; }
        public Nullable<int> PetID { get; set; }
        public string PetName { get; set; }
        public Nullable<System.DateTime> BoardingStartDate { get; set; }
        public Nullable<System.DateTime> BoardingEndDate { get; set; }
    }
}
