//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeHour
    {
        public int DayID { get; set; }
        public string DayName { get; set; }
        public System.DateTime DayStart { get; set; }
        public System.DateTime DayEnd { get; set; }
        public Nullable<System.DateTime> LunchStart { get; set; }
        public Nullable<System.DateTime> LunchEnd { get; set; }
        public bool TentativeWorkingDay { get; set; }
        public bool TentativeLunchHours { get; set; }
    }
}
