//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDocument
    {
        public int Id { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string DocumentCategory { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
