//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PatientID { get; set; }
        public int ClientID { get; set; }
        public int SpeciesID { get; set; }
        public int BreedID { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public string Breed { get; set; }
        public string Color { get; set; }
        public string Species { get; set; }
        public string Birthday { get; set; }
        public string Codes { get; set; }
        public string Rabies { get; set; }
        public string Plan { get; set; }
        public Nullable<double> Weight { get; set; }
        public string WeightType { get; set; }
        public Nullable<bool> Allergies { get; set; }
        public string Reminded { get; set; }
        public Nullable<bool> Deceased { get; set; }
        public string Microchip { get; set; }
        public byte[] Image { get; set; }
    }
}
