//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedure
    {
        public int Id { get; set; }
        public string ProcedureCategory { get; set; }
        public string ProcedureDescription { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<double> ProcedureCost { get; set; }
    }
}
